# Notion Project Reporter - Test Connection Workflow
# Validate Notion API connectivity and permissions
name: test-connection
description: "Verify Notion API authentication, database access, and configuration"
author: "Mike"

# Paths
installed_path: '{project-root}/bmad/notion-sync/workflows/test-connection'
template: false  # Action workflow - no document generation
instructions: '{installed_path}/instructions.md'

# Critical variables from config
config_source: '{project-root}/bmad/notion-sync/config.yaml'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

# Module-specific config paths
notion_config: '{project-root}/bmad/notion-sync/config.yaml'

# Notion API configuration (loaded from config)
notion_api_token: '{notion_config}:notion_api_token'
notion_database_id: '{notion_config}:notion_database_id'
current_status_block_id: '{notion_config}:current_status_block_id'
project_name: '{notion_config}:project_name'

# Invocation control
standalone: true

# Workflow metadata
complexity: simple
interaction_style: action  # Automated testing with status reports
interactivity_level: low  # Minimal user input required
theme: mission-control  # Ground Control diagnostics language
