# Design Transformation Loop Workflow Configuration
name: design-transformation
description: "Enterprise-grade design system implementation with visual feedback loops. Transforms existing designs to match reference quality (Apple, IBM, Linear, Notion-level) through iterative refinement."
author: "Mike"

# Critical variables load from config_source
config_source: "{project-root}/bmad/vde/config.yaml"
output_folder: "{config_source}:output_folder"
data_folder: "{config_source}:data_folder"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
date: system-generated

# Module-specific settings
visual_evaluation: "{config_source}:visual_evaluation"
iteration_settings: "{config_source}:iteration_settings"
quality_thresholds: "{config_source}:quality_thresholds"

# Module paths
installed_path: "{project-root}/bmad/vde/workflows/design-transformation"
template: false  # This is an interactive workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Workflow mode
mode: "interactive"  # User-driven with agent coordination

# Tool requirements
required_tools:
  - playwright_mcp  # For Capture Specialist
  - code_editing    # For Implementation Specialist
  - image_analysis  # For Visual Analyst
  - web_browsing    # For Foundation Specialist

# Agent roster (loaded from vde/agents/)
agents:
  director: "{project-root}/bmad/vde/agents/director.md"
  foundation_specialist: "{project-root}/bmad/vde/agents/foundation-specialist.md"
  capture_specialist: "{project-root}/bmad/vde/agents/capture-specialist.md"
  visual_analyst: "{project-root}/bmad/vde/agents/visual-analyst.md"
  implementation_specialist: "{project-root}/bmad/vde/agents/implementation-specialist.md"

# Runtime data storage
screenshots_folder: "{data_folder}/screenshots"
reports_folder: "{data_folder}/reports"
state_file: "{data_folder}/project-state.json"

# Safety limits
max_iterations_per_component: 50
max_time_per_component: "2 hours"
checkpoint_frequency: 5
enable_rollback: true
enable_regression_testing: true
