# Notion Project Reporter - Update Status Workflow
# Synchronize story status to Notion database and update mission log
name: update-status
description: "Sync story status to Notion database with changelog tracking"
author: "Mike"

# Paths
installed_path: '{project-root}/bmad/notion-sync/workflows/update-status'
template: false  # Action workflow - no document generation
instructions: '{installed_path}/instructions.md'

# Critical variables from config
config_source: '{project-root}/bmad/notion-sync/config.yaml'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

# Module-specific config paths
notion_config: '{project-root}/bmad/notion-sync/config.yaml'
changelog_file: '{project-root}/bmad/notion-sync/data/changelog.md'
story_map_file: '{project-root}/bmad/notion-sync/data/story-map.json'

# Notion API configuration (loaded from config)
notion_api_token: '{notion_config}:notion_api_token'
notion_database_id: '{notion_config}:notion_database_id'
current_status_block_id: '{notion_config}:current_status_block_id'
project_name: '{notion_config}:project_name'
status_mapping: '{notion_config}:status_mapping'

# User inputs collected during workflow
user_inputs:
  - story_id: "Which story to update (e.g., Story-12)"
  - new_status: "New status value"
  - update_notes: "Notes about this update"
  - update_status_block: "Whether to update current status block (yes/no)"
  - status_block_content: "Content for status block (if updating)"

# Invocation control
standalone: true

# Workflow metadata
complexity: standard
interaction_style: interactive  # Conversational questions
interactivity_level: high  # Multiple user inputs required
theme: mission-control  # Flight Director operational language
