# VDE Module Configuration
# Visual Design Excellence Suite
# Generated: 2025-10-16
# Version: 1.0.0

module_name: "Visual Design Excellence Suite"
module_code: "vde"
author: "Mike"
description: "Enterprise-grade design system implementation module with AI vision and automated visual feedback loops"

# Module paths
module_root: "{project-root}/bmad/vde"
installer_path: "{project-root}/bmad/vde"

# Component counts
agents:
  count: 5
  list:
    - director
    - foundation-specialist
    - capture-specialist
    - visual-analyst
    - implementation-specialist

workflows:
  count: 1
  list:
    - design-transformation

tasks:
  count: 0
  list: []

# Module-specific settings
visual_evaluation:
  layer1_objective:
    enabled: true
    checks:
      - wcag_contrast
      - design_token_consistency
      - grid_alignment
      - spacing_scale

  layer2_structural:
    enabled: true
    similarity_threshold: 0.90
    methods:
      - pixel_diff
      - perceptual_similarity
      - layout_comparison

  layer3_semantic:
    enabled: true
    confidence_threshold: "high"
    assessments:
      - visual_hierarchy
      - aesthetic_quality
      - vibe_match

iteration_settings:
  max_iterations_per_component: 50
  max_time_per_component: "2 hours"
  checkpoint_frequency: 5
  checkpoint_time_interval: "30 minutes"
  enable_rollback: true
  enable_regression_testing: true

quality_thresholds:
  minimum_similarity: 0.85
  target_similarity: 0.90
  layer1_pass_required: true

# Tool integrations
tools:
  playwright_mcp: true
  code_editing: true
  image_analysis: true
  accessibility_auditing: true

# Output configuration
output_folder: "{project-root}/docs/vde"
data_folder: "{project-root}/bmad/vde/data"
screenshots_folder: "{data_folder}/screenshots"
reports_folder: "{data_folder}/reports"
